version: '3.8'

services:
  react:
    build: .
    container_name: binotify-react
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
